url: https://mstreeman1.github.io
baseurl: /ms.treeman/

# Site settings
title: Hail Pretzels!
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Ms.treeMan
  pic: 1
  position: Lead Designer

- name: Ms.treeMan
  pic: 2
  position: Lead Marketer
  
- name: Ms.treeMan
  pic: 3


# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
