url: https://mstreeman1.github.io
baseurl: /ms.treeman/

# Site settings
title: Hail Pretzels!
description: "This site is a blog (which is also in fact a site) with words - by a Quintessential Stoic."


# Team names, titles and social links
people:
- name: Gyro Gearloose
  pic: 1
  position: Lead Designer

- name: Donald Duck
  pic: 2
  position: Lead Marketer
  
- name: Daffy Duck
  pic: 3
  position: Lead Programmer


# Build settings
markdown: kramdown
permalink: pretty
